environment: scw
phase: dev

minio:
  fullnameOverride: "minio"
  enabled: true
  defaultBuckets: "app"
  auth:
    existingSecret: minio-root
  ingress:
    enabled: true
    hostname: minio.external-app.cpin.numerique-interieur.com
  apiIngress:
    enabled: true
    hostname: api-minio.external-app.cpin.numerique-interieur.com
  provisioning:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  volumePermissions:
    containerSecurityContext:
      runAsUser: "auto"
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  persistence:
    enabled: true
    size: 30Gi
  resources:
    requests:
      cpu: 512m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1024Mi